### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by edmondja** [riiswa/kanrl#1]
Thanks, I wanted to do the same with upside down RL. 
Can you please also show what performance you get with MLP so we can compare ?

**Comment by riiswa** [comment]
It's very interesting, if you want, and if you have time, you can add experiments with upside-down RL to the repository :D. I'm planning to compare my implementation with a classic MLP (probably this afternoon). With a  hyperparameters search, as I have no idea what the right parameters are for KAN.

**Comment by riiswa** [comment]
@edmondja I updated the repo :D
