### ISSUE TITLE
Trying grid update?

### ISSUE THREAD

**Issue by KindXiaoming** [riiswa/kanrl#2]
Hi, thanks for trying KAN! It's interesting that you observe that KANs are more unstable than MLPs to train. Have you tried grid update like [here](https://github.com/KindXiaoming/pykan/blob/master/kan/KAN.py#L896), which in my experience is quite important for KAN to achieve good performance. Although stochasticity might be the main problem of RL, so KANs may also suffer from that. Behavior of KANs in the presence of noise is still underexplored, so thanks for trying this!

**Comment by riiswa** [comment]
Hello! and thank you for your work on KAN 😄 , I do indeed update my grid with some frequency, with the whole replay buffer as you can see [here](https://github.com/riiswa/kanrl/blob/958e6a0a0f90c7214f9ec46890ed2d1ac289d3dc/kaqn.py#L217).
However, for things to work I had to deactivate the training of certain variables, like in your continual learning experiment: bias_trainable=False, sp_trainable=False, sb_trainable=False. I'm going to continue investigating tomorrow, with other combinations of hyperparameters. It's indeed possible that stochasticity is a problem

**Comment by KindXiaoming** [comment]
Thanks! Also would be interesting to plot successful KANs (if the network is not too large) to see if the policy is interpretable (likely not with first shot), but would be fun to try!

**Comment by riiswa** [comment]
Thanks for you suggestion, I added the interpretable policy to the repo. I'm currently working on extract interpretable policy from already learned policy with MLP, is just transfer learning, and should be work great with KANs @KindXiaoming

**Comment by lilydalson9** [comment]
Your dedication to exploring novel techniques like grid updates for KAN training is commendable! It's through meticulous experimentation that we uncover the nuances of these architectures and push the boundaries of what's possible in reinforcement learning. Indeed, the journey of understanding how KANs navigate the complexities of noise is one filled with excitement and discovery.

Speaking of navigating complexities, if you're interested in mastering the intricacies of driving, why not consider [Automatic Driving Lessons](https://autodrivinginstructor.co.uk/)?
